### ISSUE TITLE
Need a way to set the flavor

### ISSUE THREAD

**Issue by AskYous** [yisraelx/ngx-showdown#9]
Hello. Thanks for making this! Is there a way we can set flavors?

**Comment by shanehsu** [comment]
You should be able to set the flavor with `ShowdownConverter` since it extends Showdown's `Converter` class 

https://github.com/yisraelx/ngx-showdown/blob/master/src/showdown-converter.provider.ts#L17
https://github.com/yisraelx/ngx-showdown/blob/master/src/base-converter.class.ts#L45

**Comment by yisraelx** [comment]
Since {[`ShowdownDirective`](https://github.com/yisraelx/ngx-showdown/blob/master/src/showdown.directive.ts), [`ShowdownPipe`](https://github.com/yisraelx/ngx-showdown/blob/master/src/showdown.pipe.ts),[ `ShowdownConverter`](https://github.com/yisraelx/ngx-showdown/blob/master/src/showdown-converter.provider.ts)} inherits from [`ShowdownConverter`](https://github.com/showdownjs/showdown/tree/1.9.0/src/converter.js) you can use the [`setFlavor`](https://github.com/showdownjs/showdown/tree/1.9.0#instance) method...

**examples**
set flavor to convertor provider.
```typescript
import { ShowdownConverter } from 'ngx-showdown';

export class SomeApp {
    constructor(showdownConverter: ShowdownConverter){
        showdownConverter.setFlavor('github');
    }
}
```
set flavor to the convertor directive.
```typescript
 import { Component, ViewChild } from '@angular/core';
 import { ShowdownDirective } from 'ngx-showdown';
 
 @Component({
   selector: 'some-component ',
   template: `
     <showdown [value]="text"></showdown>
   `,
 })
 export class SomeComponent {
     text = '# Github Flavor';
     @ViewChild(ShowdownDirective) _showdownDirective: ShowdownDirective; 
     ngOnInit() {
      this._showdownDirective.setFlavor('github');
     }
 }
```
---

Although it seems to me quite simple the available way to set flavor,
I will add in the next release a new way to set a flavor options through the ['ConverterOptions'](https://github.com/yisraelx/ngx-showdown/blob/master/src/base-converter-options.provider.ts).

https://github.com/yisraelx/ngx-showdown/blob/681c175d75dcbca674394337a5c7967917d434e2/src/base-converter-options.provider.ts#L40

[`new ConverterOptions(options?: IConverterOptions | IFlavor)`](https://github.com/yisraelx/ngx-showdown/blob/master/src/base-converter-options.provider.ts#L40)

https://github.com/yisraelx/ngx-showdown/blob/681c175d75dcbca674394337a5c7967917d434e2/src/base-converter-options.provider.ts#L44
[`ConverterOptions.prototype.marge(options?: IConverterOptions | IFlavor)`
](https://github.com/yisraelx/ngx-showdown/blob/master/src/base-converter-options.provider.ts#L44)

**example**
```typescript
 import { ConverterOptions } from 'ngx-showdown';

 let converterOptions: ConverterOptions = new ConverterOptions('vanilla');
 converterOptions.merge({
 noHeaderId: false,
 // ...
 });
 converterOptions.merge('github');
// ...
```

Or if you have a better idea, feel free to offer or to send pull request...
